### ISSUE TITLE
More functions please

### ISSUE THREAD

**Issue by tamar-borges** [suiteplus/nsmockup#1]
I need to use these functions for my developments, it would be possible to implement these functions too?

Functions:
nlapiGetFieldValue
nlapiSetFieldValue
nlapiGetRecordType
nlapiGetNewRecord
nlapiGetField
nlapiYieldScript
nlapiLoadSearch
nlapiInitiateWorkflow
nlapiTriggerWorkflow
nlapiScheduleScript
nlapiSubmitConfiguration
nlapiExchangeRate
nlapiGetLogin
nlapiLoadConfiguration
nlapiMergeRecord
nlapiRequestURL
nlapiSearchGlobal
nlapiSendCampaignEmail
nlapiSendEmail
nlapiSubmitField
nlapiTransformRecord
nlapiSubmitCSVImport
nlapiStringToDate
nlobjCSVImport

Tanks!

**Comment by danieljoppi** [comment]
You can follow: [nsmockup Roadmap](https://github.com/suiteplus/nsmockup/blob/master/ROADMAP.md).
