### ISSUE TITLE
Future of nsmockup for NetSuite API 2.0

### ISSUE THREAD

**Issue by timaschew** [suiteplus/nsmockup#11]
Since NetSuite API 2.0 is written in AMD, what is the plan of nsmockup?
Will it provide support for it?

**Comment by danieljoppi** [comment]
not now

> Important SuiteScript 2.0 is a beta feature. The contents of this feature are preliminary and may be changed or discontinued without prior notice. Any changes may impact the feature’s operation with the NetSuite application.  NetSuite warranties and product service levels shall not apply to the feature or the impact of the feature on other portions of the NetSuite application. NetSuite may review and monitor the performance and use of the feature.

**Comment by timaschew** [comment]
What you mean with `not now`?
2.0 will be released next month

**Comment by danieljoppi** [comment]
When the new NetSuite release was upgraded, I'll see what has changed, but `not now`.
The `node.js` already support the `commonJS`, that is the basis of SuiteScript 2.0.

Or I'm wrong?

**Comment by timaschew** [comment]
No, SuiteScript 2.0 supports AMD, that's the _opposite_ of CommonJS

**Comment by danieljoppi** [comment]
The first problem :disappointed: (but not big problem) ... we can use `requirejs` for AMD support. 

The problem will be, how we convert all `nlapi` Functions to the in new modules ... :mag:

The big problem is:
- I do not have time to look at that now :-1: 

We can start a little implementation in next week ... and if you want, you could see what changes these modules. And open others issues, if you find something.

**Comment by timaschew** [comment]
the files can be bundles into a UMD format which provide support for both CommonJS and AMD.
Of course you could also use requirejs in nodejs.

nlapi functions:
We need a mapping from each nlapi function to the NetSutie module name and the new function name and hoping that the arguments are the same _finger-crossed_
