### ISSUE TITLE
Example project

### ISSUE THREAD

**Issue by tamar-borges** [suiteplus/nsmockup#2]
It would also interesting a project of usage example of "nsmockup" already  configured.
Something like a "Hello World" of "nsmockup".

Not that it's difficult to use the "msmockup" but an example would be practical for  who use the first time.

Thanks.

**Comment by danieljoppi** [comment]
Help if you look at the [RESTlet Test](https://github.com/suiteplus/nsmockup/blob/master/test/create-restlet-test.js)?
