### ISSUE TITLE
underscore.js won't import

### ISSUE THREAD

**Issue by wkrueger** [suiteplus/nsmockup#7]
Tried:
- adding it as a source lib in both orders

```
            nsmockup.createRESTlet({
...
                files: [
                    '<source file>' ,
                    'node_modules/underscore/underscore-min.js',
                ]
...
);
```
- removed it from files. Instead, pasted the minified lib on the source file. Still getting

```
ReferenceError: _ is not defined
```

Suspect: maybe it has something to do with environment recognizing code inside the library (node vs browser)?

PS: underscore is used because lodash had problems with netsuite when i once tried it.

**Comment by wkrueger** [comment]
prepending the source file with `var _ = require('underscore')` did it as a workaround.

**Comment by danieljoppi** [comment]
You can add one `alias` for your library, example: 

``` javascript
          nsmockup.createRESTlet({
''...
                files: [
                    '<source file>' ,
                    ['node_modules/underscore/underscore-min.js', '_']
                ]
//...
);
```

Its a new configuration, and it will be include in release v0.10.0.

**Comment by timaschew** [comment]
alias sounds great :+1:
